name: AGRUPAMENTO LISTAS
on:
  schedule:
    - cron: '9 * * * *'
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Agrupando todas listas
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          wget https://gist.githubusercontent.com/guiworldtv/5688b42019ef511b9c2a1a4943571489/raw/e36c98960e7d775dde7e56e7ebadcc44889f82b5/TESTING%2520LINKS.M3U
          
    - name: execute py script 
      run: python agrupadordelistas.py
    
    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git commit -m "TUDO JUNTO"
        git push
