name: UCRANIA TV SIGNALS
on:
  schedule:
    - cron: '0 0/2 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: install python packages
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
    - name: execute py script 
      run:  
            pwd
            chmod +x ucraniatv.py
            ./ucraniatv.py
    
    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git commit -m "links atualizados"
        git push
